### ISSUE TITLE
Obfuscating

### ISSUE THREAD

**Issue by KnightSec-Official** [4nat/Reborn#5]
I really don't know what are you trying to hide by obfuscating this code.. It aint a big script. There are far more greater sms spammers and call spammers than this one.. aint no offense but this is an open source area.. consider uploading ur script to other websites if you wanna obfuscate em.

**Comment by 4nat** [comment]
my friend, thank you for your suggestion, I do not want to hide the codes. but my mysql database writes in the code already obfuscate does not store the code.

**Comment by nm17** [comment]
@KnightSec-Official
